### ISSUE TITLE
Remove blur on mobile devices

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#28]
The performance hit is huge even on a modern device

**Comment by djrm** [comment]
i think we can have a similar effect by scaling down the image and stretching it in the banner, this will solve the performance issues.

**Comment by djrm** [comment]
i would think it is possible to add the scaling via hugo Resize, remove the blur filter, and let the browser do the filtering by scaling the picture (this is a natural step taken given that the image will scale to cover the banner, causing a blur effect), of course this wont look as good as the filter, but i dont think it matters much since it is blured anyway.

**Comment by NathanLovato** [comment]
Ah with the template, yeah this should work. Then if the quality is lower a low-sized blur is okay on desktop to smooth out the result - it's mostly the 50px radius that hits mobile phones hard.
