### ISSUE TITLE
Convert the site's design into a hugo theme

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#41]
The website's skin is MIT but:

1. Some values and content are hard coded in the layouts and css (like the main banner image)
2. It's not super configurable
3. It's not a hugo theme so it's not as easy as it could be to plug in an existing website

It's not an issue for me and I don't have time to work on this alone, but if anyone wants to help turn the website's skin into a theme and/or improve the layouts I'll be glad to help! Just leave a message here and we can open specific issues for the things that need to be reworked.

**Comment by djrm** [comment]
Im not sure if there is much beneffit in creating a plugable theme (besides it could be quite some work), the reason why the theme is like it is now, is because for the website you dont need every widget that a theme would need also there are lots of custom stuff, also probably most people wont find much use for another custom theme (but im not sure about this)

**Comment by NathanLovato** [comment]
This task is here if someone wants to do it and use the theme for another website. I wouldn't convert the layouts to a theme just for the sake of it.
