### ISSUE TITLE
Improve gulp's tasks > gulpfile.js

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#47]
The website uses **gulp** to handle some tasks like watching and building scss, minifying html and css files, and deploying updates to github pages with gulp-deploy.

I have too much work to keep up with web development so if you do that professionally, your help would be welcome to **sanitize the build process**, minimize dependencies to make this repository more accessible to other people. It's mostly about scss watch and build, building and minifying the website, the pictures, and deploying. **The leaner the solution (fewer dependencies) the better**.

Even if you can just share some feedback and insights that'd be super valuable.

Currently rebuilding and pushing the website takes 3 steps (back when I wrote the script I couldn't get macro/gulp command dependencies to work):

```bash
hugo
gulp htmlmin
gulp deploy
```

**Comment by djrm** [comment]
Im currently using a pre-commit git hook, to call hugo, add public to the commit (optimize the assets, etc.)
The problem, is that since im not using gulp, webpack or any asset bundler (they are overkill for this), my solution is not portable, in fact it depends on some cli-tools, unfortunately you dont have much options outside the NodeJS realm, also hugo is only able to reduce the quality of jpegs (as far as i know), it does not deal with CSS minification or SVG optimization, So in terms of simplicity you could stick with gulp, since you only need to run some tasks, not bundle a lot of stuff.

**Comment by NathanLovato** [comment]
Thanks a lot for your feedback! 

Yes hugo only does image resizing and compression for jpg and pngs iirc. But it's a bit awkward as it's part of the templating language and you've got to use e.g. shortcodes inside of your content to tell it to process individual images.

Okay so that's great if we can stick with gulp :). Gonna change the task so if anyone has a moment to clean up the gulpfile.js... it'd be nice to automate image compression, minifying and maybe deploy in one step.
